[unstable]
# コアとallocとコンパイラ組み込みのみのライブラリを再コンパイルする
build-std = ["core", "compiler_builtins", "alloc"] 
# memsetなどを有効化する
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"